# Generated by Django 3.2 on 2021-04-18 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
